pipeline:
  name: manasa-ppln
  identifier: manasappln
  projectIdentifier: SFTY_Training
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githubnothing
        build: <+input>
  stages:
    - stage:
        name: github-123
        identifier: github123
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec: {}
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: docker123
                    repo: manasa1docker/new-img
                    tags:
                      - v1
                    dockerfile: Dockerfile
                    context: .
